### ISSUE TITLE
Error "cbor.h: no such file or directory" when compiling for Zephyr

### ISSUE THREAD

**Issue by kiendinh** [iotivity/iotivity-constrained#1]
I got following error when compiling the Zephyr app. I'm at 49dba3a and Zephyr was set to v1.5.0 release.

$ make pristine && make
...In file included from /home/kien/workspace/iotivity-constrained/port/zephyr/../../include/oc_ri.h:21:0,
                 from /home/kien/workspace/iotivity-constrained/port/zephyr/../../messaging/coap/separate.h:42,
                 from /home/kien/workspace/iotivity-constrained/port/zephyr/../../messaging/coap/oc_coap.h:20,
                 from /home/kien/workspace/iotivity-constrained/port/zephyr/../../include/oc_api.h:20,
                 from /home/kien/workspace/iotivity-constrained/port/zephyr/src/../../../apps/server_zephyr.c:17:
/home/kien/workspace/iotivity-constrained/port/zephyr/../../include/oc_rep.h:20:36: fatal error: deps/tinycbor/src/cbor.h: No such file or directory
compilation terminated.
make[3]: **\* [src/../../../apps/server_zephyr.o] Error 1
make[2]: **\* [zephyr-app-dir] Error 2
make[2]: Leaving directory `/home/kien/workspace/iotivity-constrained/port/zephyr/outdir/qemu_x86'
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory`/home/kien/workspace/zephyr/zephyrLF'
make: **\* [all] Error 2
(master)kien:zephyr$ pwd
/home/kien/workspace/iotivity-constrained/port/zephyr

**Comment by kmaloor** [comment]
Hello,
It appears that you haven't pulled tinycbor into your IoTivity-Constrained source tree.
Please follow the step under "Pull Dependencies" in the README.

**Comment by kiendinh** [comment]
Thanks, I followed instructions in the README and it could compile now.
