### ISSUE TITLE
how to compatible iotivity-constrained to iotivity?

### ISSUE THREAD

**Issue by ustccw** [iotivity/iotivity-constrained#14]
Hi,
need your help!  what should i do to compatible iotivity server in this repo with iotivityclient.apk?
the problem depicts as the following:  

1. start iotivity server:
   i  compile this repo by `make DEBUG=1` on ubuntu16.04 and start it. 

```
$ cd iotivity-constrained/port/linux
$ make clean 
$ make DEBUG=1
$ ./server
```

2. start iotivity client by  the iotivity.apk:  
![iotivity-icon](https://user-images.githubusercontent.com/24221485/34434626-46c0c27a-ecc2-11e7-8908-b58e8d5615f8.jpg)

3.  they cannot interact with each other, the trace shows as the following:
3.1 apk send Coap package with Option 2049:  
![apk_coap_send](https://user-images.githubusercontent.com/24221485/34434739-2cd4d120-ecc3-11e7-9620-743c99bf5ed8.png)  

3.2 iotivity server refuse the client:
![coap_code_ret](https://user-images.githubusercontent.com/24221485/34434752-45ec4cc4-ecc3-11e7-9edd-330371628aa5.png)

3.3 the server log is:  
![coap_log](https://user-images.githubusercontent.com/24221485/34434762-55c242de-ecc3-11e7-8d9d-f6fcba9494d0.png)

can you help to solve it?

**Comment by kmaloor** [comment]
@ustccw You seem to be using a very old version of the code. Try with the latest code from the master branch.

**Comment by ustccw** [comment]
@kmaloor tks for your advice, i would try it.
